### ISSUE TITLE
Sending command upon connect

### ISSUE THREAD

**Issue by BMitrovic17** [Throne3d/node-irc#70]
Is there a way to send a command upon successful connect?

I've tried something along the lines of:
```
bot.addListener('registered', function() {
	bot.send('mode', bot.nick, '+B');
	bot.send('privmsg: vhost user pass');
});
```
but unfortunately this fails. (`+B` does get applied) Any advice ?

**Comment by Throne3d** [comment]
Hmm, that's exactly what discord-irc does ([here](https://github.com/reactiflux/discord-irc/blob/308766163a37400daf2a77e7391fd1edac185716/lib/bot.js#L130-L136)), so that leads me to think something's going wrong in the specific interaction with the server (like the server rejecting your attempt to set that mode).

I'd recommend enabling `debug` or `showErrors` in [the client config](https://node-irc-upd.readthedocs.io/en/latest/API.html#client). Check there to see that the bot agrees it's sending the mode command, and then see if there's an error from the server.

(Separately, I'm not sure what that colon is doing in `privmsg: vhost user pass`. I'm pretty sure you want something like `PRIVMSG vhost :user pass` – or you can simply use `bot.say('vhost', 'user pass')`.)

**Comment by Throne3d** [comment]
I'm gonna close this for inactivity. If you're still having trouble, please feel free to comment with more information.
